name        : python-gtk2
version     : 2.24.0
release     : 5
source      :
    - http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2 : cd1c1ea265bd63ff669e92a2d3c2a88eb26bcd9e5363e0f82c896e649f206912
homepage    : http://www.pygtk.org
license     : GPL-2.0
component   : programming.python
summary     : GTK+2 bindings for Python
description : |
    python-gtk lets you to easily create programs with a graphical user interface using the Python programming language and GTK+2 library.
builddeps   :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-2.0)
rundeps    :
    - python-cairo
    - python-gobject2
setup      : |
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
