name       : python-gtk2
version    : 2.24.0
release    : 7
source     :
    - https://download.gnome.org/sources/pygtk/2.24/pygtk-2.24.0.tar.gz : 6e3e54fa6e65a69ac60bd58cb2e60a57f3346ac52efe995f3d10b6c38c972fd8
homepage   : http://www.pygtk.org
license    : GPL-2.0
component  : programming.python
summary    : GTK+2 bindings for Python
description: |
    python-gtk lets you to easily create programs with a graphical user interface using the Python programming language and GTK+2 library.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-2.0)
rundeps    :
    - python-cairo
    - python-gobject2
setup      : |
    %patch -p1 < $pkgfiles/drop-pangofont.patch
    %patch -p1 < $pkgfiles/fix-leaks-of-pango-objects.patch
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
